### PR TITLE
Update medium.php

### PR DESCRIPTION
**Pull request by wscrawford**
Content filters require updating for refactor of Pages to Articles.

### CODE REVIEW

**Comment by rmdstudio** [comment]
@wscrawford why is photo replaced with article in the media content plugin?

**Comment by wscrawford** [comment]
My bad, there are two instances of pages, appears I mis-took the instance of photos as the second instance of pages.

**Comment by rmdstudio** [comment]
thank you @wscrawford  :+1:

**Comment by wscrawford** [comment]
@rmdstudio I noticed the Video content filter is not being applied from within com_articles as it should be and is within com_pages.  Looking into the content filter itself I couldn't work out why that might be the case - the medium content filter included references to pages in the $pattern matching but I didn't see anything analogous in the video content filter.

Can you think where this would be found?

**Pull request merged**
